FundingCircle/jackdaw

- src/jackdaw/admin.clj
Fixes #9, which correctly points out that I typo'd this code and it never worked.
> Fix failure to use topics

- README.md
Replace the checked-in version string with the clojars latest badge.
> Cut over to the clojars badge

- project.clj
- cleanup unused dependencies
- move codox and git-version plugin to dev profile
> Cleanup unused dependecies

- README.md
- project.clj
Add a cljdoc badge and a url key (which will allow Clojars to link to this repo)
> Cljdoc badge and url

- examples/word-count/src/word_count.clj
- examples/word-count/test/word_count_test.clj
- src/jackdaw/serdes/edn.clj
- src/jackdaw/test/fixtures.clj
- test/jackdaw/test/fixtures_test.clj
A few stylistic suggestions to #102 
- make topic-metadata [the best function it can be](https://youtu.be/YR5WdGrpoug?t=1066)
- update the test so that it closes the driver
- add an "empty-state" fixture that is nice to have in-case there's any state left-over from a failed test-run
> Word count improvement fixes

- README.md
> supported versions of Clojure

- src/jackdaw/admin.clj
- src/jackdaw/data.clj
- src/jackdaw/serdes/avro.clj
- src/jackdaw/serdes/resolver.clj
- src/jackdaw/streams/mock.clj
- src/jackdaw/test/commands/watch.clj
- src/jackdaw/test/journal.clj
- src/jackdaw/test/middleware.clj
- src/jackdaw/test/transports.clj
- src/jackdaw/test/transports/rest_proxy.clj
Various fixes suggested by the linter and kibit.
> Minor fixes and cosmetics

- README.md
> clarify link to documentation

- examples/word-count/deps.edn
> Fix #129 by pulling in v0.6.4 to the word-count example

- .github/CONTRIBUTING
- CHANGELOG.md
- doc/DCO_+_LICENSE
A changelog is a file which contains a curated, chronologically ordered list of notable changes for each version of a project.
To make it easier for users and contributors to see precisely what notable changes have been made between each release (or version) of the project.
People do. Whether consumers or developers, the end users of software are human beings who care about what's in the software. When the software changes, people want to know why and how.
https://keepachangelog.com/en/1.0.0/
This PR also includes a "strawman" contributing guide to gently nudge contributions to include a changelog (as well as other guidelines that aim to describe what high-quality contributions look like)
> Let's keep a CHANGELOG

- CHANGELOG.md
- CONTRIBUTING.md
- examples/pipe/deps.edn
- examples/serdes/deps.edn
- examples/simple-ledger/deps.edn
- examples/word-count/deps.edn
* Update changelog and Jackdaw version for examples.
* Remove the "Reporting bugs" subheading from CONTRIBUTING.md.
> Update Changelog for 0.6.4

- src/jackdaw/serdes/avro.clj
- test/jackdaw/serdes/avro_test.clj
Coerces clojure number values to avro int/long when possible.
> Coerce clojure numbers to avro numbers

- src/jackdaw/test/commands.clj
- test/jackdaw/test/commands_test.clj
- test/jackdaw/test_test.clj
> Do not assume result of executing command is already a map

- src/jackdaw/admin.clj
- test/jackdaw/admin_test.clj
Signed-off-by: Josip Gracin <josip.gracin@gmail.com>
> Fix issue #192 in topics-ready? - dereferencing deferred

- src/jackdaw/test/transports/rest_proxy.clj
- test/jackdaw/test/transports/rest_proxy_test.clj
This change aims to allow test-machine users to supply their own consumer group configuration parameters when creating a test-machine that uses the rest-proxy. The allowed parameters are described in the [API Docs](https://docs.confluent.io/current/kafka-rest/api.html#post--consumers-(string-group_name)).
One feature this is intended to support is to get the test-machine to read from the beginning of some topic that exists in another environment. This will allow users to retrieve data from e.g. production or staging environments, and run it through a test version of the application running on a developer machine without requiring access to the broker itself which can then be locked down for security purposes. Once [this rest-proxy …
> Add ability to configure the group-config when creating a rest-proxy

- .github/pull_request_template.md
- CHANGELOG.md
- add unreleased section with 2 changes
- add pr template
> pr template and add unreleased section

- CHANGELOG.md
Time to do a release 🎉. Let's get sync the changelog
> Catch the changelog up with merged PRs

- CHANGELOG.md
- project.clj
- src/jackdaw/serdes.clj
- src/jackdaw/serdes/fressian.clj
- test/jackdaw/serdes/fressian_test.clj
> Add Fressian Serde via clojure.data.fressian

- src/jackdaw/client.clj
> Add type hint to fix reflection warning

- CHANGELOG.md
- doc/admin.md
This is a first stab at providing a small guide to the `jackdaw.admin` namespace.
- ~[] tests~
- ~[ ] updated [CHANGELOG](../CHANGELOG.md) (the "unreleased" section)~
> Add an article about jackdaw.admin

- .circleci/config.yml
- CHANGELOG.md
- project.clj
💁 Updates the version of 
* Leiningen
* Confluent Platform components
in the CircleCI build configuration.
> Update dependencies in CircleCI build

- CHANGELOG.md
- src/jackdaw/data/producer.clj
- test/jackdaw/data_test.clj
> Null-able ProducerRecord and RecordMetadata members

- test/jackdaw/streams_test.clj
Just a basic test to demonstrate how to produce a stream of diffs based off some input topic using the jackdaw streams DSL. This kind of thing has been asked a few times in various forums so it's nice to have an example to point to in the tests.
> Add test to demonstrate production of a diff stream

- doc/client.md
> Fix for producer docs

- test/jackdaw/specs_test.clj
Quick follow, test coverage for the new utility added to the specs ns.
- [_] updated [CHANGELOG](../CHANGELOG.md) (the "unreleased" section)
> test coverage for a new util

- CHANGELOG.md
Preparing to cut a release / deploy.
- [_] tests
- [_] updated [CHANGELOG](../CHANGELOG.md) (the "unreleased" section)
> putting in a Changelog date for the release

- doc/streams.md
Add a few `clojure` where missing in the streams docs.
> Use clojure lang in markdown

- CHANGELOG.md
- src/jackdaw/streams/interop.clj
- src/jackdaw/streams/specs.clj
- test/jackdaw/streams_test.clj
Re: https://github.com/FundingCircle/jackdaw/issues/248
> Use store-name override in 2-arity ktable constructor

- CHANGELOG.md
- project.clj
~- [ ] tests~
- [✔️] updated [CHANGELOG](../CHANGELOG.md) (the "unreleased" section)
addresses #256
> Bump clj UUID

- CHANGELOG.md
- src/jackdaw/serdes/avro.clj
This change is tested against SBA connector project and looks fine.
> Replacing deprecated methods in avro with supported methods

- CHANGELOG.md
- src/jackdaw/serdes/avro.clj
- src/jackdaw/serdes/avro/confluent.clj
- src/jackdaw/serdes/resolver.clj
- test/jackdaw/serdes/resolver_test.clj
> Serde properties

- .circleci/config.yml
> [TDI-2564] Removes codecov

- CHANGELOG.md
- project.clj
- src/jackdaw/streams/extras.clj
> Drop clj time

- CHANGELOG.md
> Prepare release 0.9.5

- CHANGELOG.md
- project.clj
> Fix repo vector typo

- CHANGELOG.md
- README.md
> Trivial change for deployment tag fix

- CHANGELOG.md
- project.clj
- src/jackdaw/serdes/json_schema/confluent.clj
- test/jackdaw/serdes/json_schema/confluent_test.clj
JSON _SR Serde wasn't correctly clojurizing deeply nested maps
> [Fix] correctly clojurize deeply nested JSON

- CHANGELOG.md
> Prepare 0.9.9 release

- CHANGELOG.md
> Update CHANGELOG.md for next release

- CHANGELOG.md
Update CHANGELOG for 0.9.11 release
> CHANGELOG for release

- CHANGELOG.md
> changelog for 0.9.12
