- src/jackdaw/streams.clj
- src/jackdaw/streams/configured.clj
- src/jackdaw/streams/interop.clj
- src/jackdaw/streams/protocols.clj
- src/jackdaw/streams/specs.clj
- test/jackdaw/streams_test.clj
Corrects the kstream->ktable left-join fn arity which accepts the serdes, as the [contract](https://kafka.apache.org/20/javadoc/org/apache/kafka/streams/kstream/KStream.html#leftJoin-org.apache.kafka.streams.kstream.KTable-org.apache.kafka.streams.kstream.ValueJoiner-org.apache.kafka.streams.kstream.Joined-) now requires a `Joined` instance
> correct kstream->ktable left-join fn args

- project.clj
This PR cuts over to `lein-git-version`, same as we use some other projects and was used to deploy `0.4.0` at the conj.
> lein-git-version

- .circleci/config.yml
This will make sure that also PRs from forks are able to run tests.
The alternatives could be:
- use docker images directly instead of the confluent package
- publish our private image somewhere
(both will potentially be faster than this solution since they enable more caching, but this solution is probably the easiest and unblocks anyone who would want to contribute from a forked repo right now)
> use public lein and install needed packages for confluent

- src/jackdaw/streams/mock.clj
- test/jackdaw/streams_test.clj
When using strings as keys, the wrong method for creating
ConsumerRecords is used. This fixes that by explicitly using the most
specific underlying method.
Closes #19
> Fix record creation for topics with string keys

- src/jackdaw/serdes/edn.clj
- test/jackdaw/serdes/edn_test.clj
Hello, 
I would like to use custom EDN readers with the EDN serde. This patch allows passing options to `edn/read-string` and make this configurable.
Would you like to merge this?
Thanks, r0man.
> Make EDN serde configurable

- test/jackdaw/serdes/edn_test.clj
`gen/any-printable` would sometimes return `Double/NaN`, which is never equal to itself, causing the round trip equality test to fail.
Fixes issue #26 
=> (= ##NaN ##NaN)
false
=> (= Double/NaN Double/NaN)
false
&c.
> Alter EDN serde test to use 100 random chars and not any-printable

- .circleci/config.yml
The existing circleci configuration must tweak the apt settings on the test runner before installing the confluent tools and running them as a separate process alongside the test. CircleCI allows for secondary images to be run alongside the primary test image for the purpose of providing external services required by a test suite. This PR makes the required services available by getting circleci to launch the secondary images meaning the main build/test tasks can focus on downloading and caching dependencies and then simply running the test.
Structuring the config in this way also makes it more manageable to test against multiple versions of kafka. For example, we could test against prior versions with something like this...
> Use docker for external services in CI

- examples/dev/user.clj
- examples/pipe/deps.edn
- examples/simple-ledger/deps.edn
- examples/simple-ledger/src/simple_ledger.clj
- examples/word-count/deps.edn
- examples/word-count/dev/system.clj
- examples/word-count/resources/metamorphosis.txt
- examples/word-count/src/word_count.clj
- src/jackdaw/client/log.clj
- Fixes a bug in `user/get-records` that prevented retrieval of more than 500 records.
- Fixes a bug in `jackdaw.client.log/log-until`.
- Extends the `word-count` and `simple-ledger` examples to match the treatment used in Clojure/conj.
> Examples from Clojure/conj 2018

- src/jackdaw/client.clj
There seems to be a bug in the `produce!` method, it either discards the `key` argument completely or it replaces it with `topic`.
> fix produce! to accept key

- project.clj
The lein-git-version plugin is required in more than just the `:dev` profile. Lets reinstate it back at the top level for now and we can discuss where it should go.
> Fix release automation

- .circleci/config.yml
Now the test logs are going to a file, we can upload them to S3 and make them available as build artifacts with this one simple trick.
> Store test logs as artifacts in circleci

- src/jackdaw/test/fixtures.clj
- test/jackdaw/serdes/avro/integration_test.clj
This might help with some of the intermittent test failures we see where it seems like the schema-registry is not up yet. Following this recommendation from the docker team....
The best solution is to perform this check in your application code, both
at startup and whenever a connection is lost for any reason.
Test-suites can quite reasonably be considered "your application" in this context
so this PR adds a `service-ready?` fixture that test authors can use to easily ensure that
some service is accepting requests before they begin their tests. An example of it's use is...
```
(deftest my-cool-test
(fix/with-fixtures [(fix/service-ready? {:http-url "http://my-cool-service"
:http-timeout 5000})]
(is (rad? (http/get "http://my-cool-service")))
```
> Add service-ready? fixture to block in tests until services are ready

- project.clj
- src/jackdaw/test.clj
- src/jackdaw/test/commands/write.clj
- src/jackdaw/test/fixtures.clj
- src/jackdaw/test/journal.clj
- src/jackdaw/test/transports/identity.clj
- src/jackdaw/test/transports/kafka.clj
- src/jackdaw/test/transports/mock.clj
- src/jackdaw/test/transports/rest_proxy.clj
- test/jackdaw/test/commands/watch_test.clj
- test/jackdaw/test/transports/kafka_test.clj
- test/jackdaw/test/transports/mock_test.clj
- test/jackdaw/test/transports/rest_proxy_test.clj
Replaces all use of core.async with the equivalent manifold construct. Basically, this means..
- replacing `channel`s with `stream`s
- replacing `go-loop`s with `d/loops`s
- wrapping the bodies of the `go-loops` into `d/chain` handlers
This means we can remove the unnecessary dependency on core.async which can cause problems depending on the downstream application's other dependencies.
Also fixed a startup bug in the kstreams fixture that results in the possibility of tests being commenced without the app under test having reached the started state.
> Use manifold for all async in the test-machine

- .circleci/config.yml
- project.clj
This PR adds a circleci workflow for automatically pushing tagged releases to clojars. The workflow only runs for tags, not branches.
To actually trigger a release therefore, there are a couple of options...
- use the github release UI to create a release that when published, will commit a corresponding tag to the repo
- at the command line, something like `git tag -a v0.5.2 -m "Release v0.5.2"`
Maybe resolves #35
> Auto-deploy to clojars for pushed tags matching /^\d+.\d+.\d+/

- project.clj
- src/jackdaw/admin.clj
- test/jackdaw/admin_test.clj
- test/jackdaw/test/transports/rest_proxy_test.clj
I looked into the admin ns because it had quite low test coverage. Think I might have found a bug and hopefully improved test coverage a bit with some of the easier tests. The remaining functions will be a bit more difficult because the MockAdminClient doesn't cover all the methods we use on the AdminClient.
> Backfill unit tests for jackdaw.admin

- src/jackdaw/test/transports/rest_proxy.clj
One of our older apps publishes messages with null message keys 😢...
> Support nil message keys in the rest-proxy

- .circleci/config.yml
- README.md
- project.clj
Extracts the cloverage part out of #16. Back when that was first created, the ci pipeline was a bit more complicated. Much simpler to run code coverage as part of the test step now.
> Report test coverage to codecov

- src/jackdaw/streams/interop.clj
Try to suppress reflection warnings by adding more type hinting in the interop namespace.
> Add type-hints in interop to suppress reflection warnings

- src/jackdaw/client.clj
- src/jackdaw/data/common.clj
- test/jackdaw/client_test.clj
Adds a bunch of tests for the client namespace. This PR covers the following aspects.
- basic consumer/producer creation and teardown
- send!, produce!
- topic subscription and assignment
- topic partition interrogation
There's still a bit more that remains without tests like offset setting/getting but these features are used by the test-machine's own test-suite.
> Add integration tests for client namespace

- src/jackdaw/client.clj
- src/jackdaw/data/common.clj
- src/jackdaw/data/consumer.clj
- test/jackdaw/client_test.clj
This PR focuses on testing the facilities provides by the client namespace to seek to some known point in a topic. For example
- seek to the beginning of a topic
- seek to the end of a topic
- seek to last offset before some timestamp
The tests for this work by creating a randomly named topic and seeing it with a few records. The test then exercises each scenario above and checks that the consumers next offset is as expected.
> Add tests for client seek behavior

- src/jackdaw/admin.clj
- src/jackdaw/client.clj
- src/jackdaw/client/log.clj
- src/jackdaw/client/partitioning.clj
- src/jackdaw/data/admin.clj
- src/jackdaw/data/common.clj
- src/jackdaw/data/producer.clj
- src/jackdaw/streams/extras.clj
- Adds `(into {})` to describe-topics-configs because `AdminClient/describeConfigs` retunrs a java map not a clojure map.
- Fix call to `subscribed-consumer` that now expects an array of topics
- Fix `offsets-for-times` call expecting a map not a sequence
- Fix `seek-to-timestamp`
- Fix call in `partitioning/->ProducerRecord` to `jackdaw.data/->ProducerRecord` with invalid topic name parameter
- Fix `->ConfigEntry` that supports key -> value  and the datafied version of Config
- Add missing PartitionInfo->data 
- Fix calls to `js/to` that where called as `js/to!`
- Change some destructured key map arguments not have the colon before the key as is most common to use that syntax
> Miscellaneous fixes/consistency changes

- project.clj
The `lein-git-deps` plugin uses the branch name as part of the filename when building a jar (or rather our configuration of it does). This just replaces anything not in `[a-zA-Z0-9]` in the branch name with an underscore in the generated jar (and subsequent publication to clojars)
> Sanitize branch names for things that shouldn't be in a filename

- src/jackdaw/test.clj
- src/jackdaw/test/transports.clj
- src/jackdaw/test/transports/identity.clj
- src/jackdaw/test/transports/kafka.clj
- src/jackdaw/test/transports/mock.clj
- src/jackdaw/test/transports/rest_proxy.clj
- test/jackdaw/test_test.clj
Fixes a few bugs I've found recently in the test-machine..
1. make sure all supported transports are loaded
2. given an empty test, `run-test` tries to run the "first" command even if no such command exists
> Test machine bug fixes

- src/jackdaw/serdes/resolver.clj
When we attempt to use the jackdaw resolver with the keyword
`:jackdaw.serdes/string-serde`, the keyword cannot be resolved into the 
serde function it is supposed to be. So we import the namespace into the resolver.
> Imported jackdaw.serdes namespace to resolver

- src/jackdaw/test/commands/write.clj
- src/jackdaw/test/transports/kafka.clj
There are some old logging statements that make tests which produce lots of data overly verbose. And  the test-producer should cast the partition to an int.
> Hackathon fixes

- project.clj
`lein deps :tree` reports a few warnings about dependency conflicts and these warnings typically propagate through to projects that use jackdaw so it's good to fix here if possible.
The main warnings were...
```
[danlentz/clj-uuid "0.1.7"] -> [primitive-math "0.1.4"]
overrides
[aleph "0.4.6"] -> [byte-streams "0.2.4"] -> [primitive-math "0.1.6"]
```
and 
```
[io.confluent/kafka-schema-registry-client "5.1.2"] -> [com.fasterxml.jackson.core/jackson-databind "2.9.6"]
overrides
[org.apache.kafka/kafka-streams-test-utils "2.2.0"] -> [org.apache.kafka/kafka-streams "2.2.0"] -> [org.apache.kafka/connect-json "2.2.0" :exclusions [*/javax.ws.rs-api]] -> [com.fasterxml.jackson.datatype/jackson-datatype-jdk8 "2.9.8"] -> [com.fasterxml.jackson.core/jackson-databind "2.9.8"]
```
This PR just adds …
> Resolve dependency conflicts reported by lein deps :tree

- src/jackdaw/test/fixtures.clj
This fixes a typo in the 2nd condition of the `service-ready?` fixture which could cause the service to be declared ready before it is actually responding with an HTTP code of 200.
This might be what is causing the rest-proxy test to sometimes fail due to commencing the test before the service is properly ready.
> Fix typo in service-ready? fixture

- src/jackdaw/test/transports/mock.clj
- test/jackdaw/test/transports/mock_test.clj
I think this should fix the issue with the word-count demo found by @matthias-margush https://github.com/FundingCircle/jackdaw/issues/114#issuecomment-486337672. The problem was that the `TopologyTestDriver` was not being closed along with all the other test resources. We just had to add it to the `:exit-hooks` for the mock transport.
> Make sure mock driver is properly closed after use

- src/jackdaw/streams.clj
- src/jackdaw/streams/configured.clj
- src/jackdaw/streams/interop.clj
- src/jackdaw/streams/protocols.clj
- src/jackdaw/streams/specs.clj
- test/jackdaw/streams_test.clj
Wraps these new arities of `aggregate` and `reduce`:
* [KGroupedTable.aggregate](https://kafka.apache.org/20/javadoc/org/apache/kafka/streams/kstream/KGroupedTable.html#aggregate-org.apache.kafka.streams.kstream.Initializer-org.apache.kafka.streams.kstream.Aggregator-org.apache.kafka.streams.kstream.Aggregator-)
* [KGroupedTable.reduce](https://kafka.apache.org/20/javadoc/org/apache/kafka/streams/kstream/KGroupedTable.html#reduce-org.apache.kafka.streams.kstream.Reducer-org.apache.kafka.streams.kstream.Reducer-)
* [KGroupedStream.aggregate](https://kafka.apache.org/20/javadoc/org/apache/kafka/streams/kstream/KGroupedStream.html#aggregate-org.apache.kafka.streams.kstream.Initializer-org.apache.kafka.streams.kstream.Aggregator-)
* [KGroupedSteam.reduce](https://kafka.apache.org/20/javadoc/or …
> Adds wrappers for reduce & aggregate arities with implicit key value stores

- CHANGELOG.md
- CONTRIBUTING.md
`CHANGELOG.md`:
* Deletes the release summary from `0.6.2`
* Capitalizes list items
* Adds missing items so we can release
* Adjusts order to reflect history
`CONTRIBUTING.md`:
* Moves `.github/CONTRIBUTING` to `CONTRIBUTING.md`
* Changes PR commit example to imperative form ("add", not "added")
* Updates numbers to match order in which links appear
* Adds sign-off step and link
> Contributing Tweaks

- project.clj
Users wishing to use the mock topology test driver currently have to explicitly depend on org.apache.kafka/kafka-streams-test-utils or else they run into ClassNotFound exceptions.
> Include kafka-streams-test-utils so jackdaw users don't have to

- doc/test-machine.md
- src/jackdaw/test/commands/base.clj
- test/jackdaw/test/commands/base_test.clj
Added two new Test Machine commands.
`:do!` - like `do` but the function provided is passed the journal atom, not the contents of the journal atom.
`:inspect` - the function provided is passed the whole test machine state (a debugging hook)
> Add more test machine commands for inspecting its state

- src/jackdaw/test.clj
- src/jackdaw/test/journal.clj
- src/jackdaw/test/transports/kafka.clj
- src/jackdaw/test/transports/mock.clj
- src/jackdaw/test/transports/rest_proxy.clj
- test/jackdaw/test/transports/kafka_test.clj
- test/jackdaw/test/transports/mock_test.clj
- test/jackdaw/test/transports/rest_proxy_test.clj
- test/jackdaw/test_test.clj
When working with the test-machine, it makes for a significantly better developer workflow when any exceptions that occur are bubbled back up to the main thread. Prior versions were catching errors and sometimes not even logging them (mea culpa!).
This PR adds tests with a few of the errors we've seen developers make and ensures that the resulting exception (including the full cause trace) is logged and the exception is bubbled back up to the main thread after all the resources used by the test are torn back down.
> Stop swallowing errors in test-machine

- src/jackdaw/streams/interop.clj
- test/jackdaw/streams_test.clj
Before this change, trying to use `kstreams` would fail because it was
missing the Consumed argument.
The newly added test would throw an exception like this:
```
Error in KStream
Uncaught exception, not in assertion
error: org.apache.kafka.streams.errors.StreamsException: Exception caught in process. taskId=0_0, processor=KSTREAM-SOURCE-0000000000, topic=topic-a, partition=0, offset=0, stacktrace=org.apache.kafka.streams.errors.StreamsException: A serializer (key: org.apache.kafka.common.serialization.LongSerializer / value: org.apache.kafka.common.serialization.LongSerializer) is not compatible to the actual key or value type (key type: clojure.lang.Symbol / value type: clojure.lang.Symbol). Change the default Serdes in StreamConfig or provide correct Serdes via method parameters.
at …
```
> Fix kstreams

- src/jackdaw/streams.clj
- src/jackdaw/streams/configured.clj
- src/jackdaw/streams/interop.clj
- src/jackdaw/streams/lambdas.clj
- src/jackdaw/streams/lambdas/specs.clj
- src/jackdaw/streams/protocols.clj
- src/jackdaw/streams/specs.clj
- test/jackdaw/streams_test.clj
The `aggregate` method of `SessionWindowedKStream` expects a `Merger`
argument.
If you try to aggregate without the Merger arg, you get this error:
`org.apache.kafka.streams.kstream.Materialized cannot be cast to org.apache.kafka.streams.kstream.Merger`
In this PR I add a merger to the lambdas namespace and adjust various
signatures to account for the extra argument.
Signed-off-by: Sam Brauer <sbrauer@rentpath.com>
> Add merger for session window aggregation

- src/jackdaw/streams.clj
- src/jackdaw/streams/interop.clj
There are 8 references in the code (and code hint in Cursive) to `global-kstream`, that should read `global-ktable` instead.
> Rename misnamed global-kstream with global-ktable

- CONTRIBUTING.md
Adds documentation so that it is easy for contributors to set their local environment up to do the right thing vis-a-viz git sign-off but also ensure it's just a one-liner to fix up the history when we forget.
Signed-off-by: Andy Chambers <andy.chambers@fundingcircle.com>
> Add docs to minimize git sign-off overhead

- src/jackdaw/serdes/avro.clj
- test/jackdaw/serdes/avro_test.clj
During the coercion phase of avro deserialisation, just assuming that a given `GenericData$Record` is the correct one purely on the basis that it is a `GenericData$Record` isn't enough if the record in question is one of several in a union type - the result is that the first record from the union every time.
This PR changes the logic so that the given `Record` only is considered to "match" if the schema itself matches the schema attached to the `Record` by avro itself.
> Select matching record from union for coercion during deserialisation.

- doc/streams.md
Remove unnecessary bracket in one of the code examples.
> Fix a typo in code example

- src/jackdaw/serdes/avro.clj
- src/jackdaw/serdes/resolver.clj
- test/jackdaw/serdes/avro_test.clj
I believe this resolves a few issues including #152, #137. It also represents part of the work required to resolve #136 although that might need a bit more work on the serialization side and could certainly use a test and documentation to demonstrate it's use. I plan to follow up on this with another guide in the docs section all about configuring the various kafka client entities (e.g. producers, consumers, serdes etc).
The main change is to add a `:deserialization-properties` optional keyword to the confluent serde constructor. Including the property "specific.avro.reader" in these properties means that any schema supplied to the deserializer will be used in combination with the writer's schema to decode the message. The reader schema must be compatible with the writer's schema in order …
> Decouple avro reader and writer serdes

- doc/client.md
- doc/clients.md
Documentation (in the form of an article) for the lower-level client API. Includes simple examples for both consuming and producing data. Tries to highlight the key points required to understand how to use the API and provide links to the relevant upstream documentation where applicable.
> Add doc/article for the jackdaw client API

- project.clj
Jackdaw already requires its users to use 1.10, so it should use it
too.  Aviso logging needed a bump up to avoid a syntax error in
previous 0.3.1.
> Upgrade clojure to 1.10.1

- CHANGELOG.md
- src/jackdaw/streams/interop.clj
- test/jackdaw/streams_test.clj
There's already a `topic->materialized` helper function, which I've
reused.
Signed-off-by: Alexis Lee <alee@greshamtech.com>
> Supply `key-serde` as well as `value-serde` in `aggregate` methods

- CHANGELOG.md
I figured before upgrading Kafka to 2.3.0 (#158), we should make a release containing the recent bug fixes and additional documentation.
I did have a look at the upgrade notes and it seems like it shouldn't break anything in jackdaw but cutting a release without it seems like it would gives folks an option to get the bug-fixes without buying into a whole new kafka version.
> Update Changelog for v0.6.7

- .circleci/config.yml
- project.clj
- test/jackdaw/admin_test.clj
- use kaocha to run tests (https://github.com/lambdaisland/kaocha)
- merge the only test profile setting into dev
- remove lein-cloverage
- support the test failure summary in circleci by publishing the test results
A failure will look like this with this change:
> Better test runner

- examples/word-count/test/word_count_test.clj
- src/jackdaw/test/fixtures.clj
- test/jackdaw/test/fixtures_test.clj
Issue #176 was already fixed by #179 although the fix was not backed by a unit test. @7vs and I (@cddr) had already begun working on this when @kidpollo submitted #179 but figured we'd continue as this PR back-fills a unit-test for the feature and also adds the ability for the user of the fixture to supply optional parameters, and an optional `reset-fn` which allows the unit test to check that the error case is handled with an informative exception (the StreamsResetter quite often fails in a dev environment when the state can easily become inconsistent but the error message usually contains enough information about what to do to resolve the situation.
> [ISSUE-176] allow reset-application-fixture to get bootsrap.servers from app-config

- doc/test-machine.md
- src/jackdaw/test.clj
- test/jackdaw/test_test.clj
It's not immediately clear when something went wrong, specially in case of timeouts.
Having it failing noisily and printing out the command that failed would help a lot while writing a new test or debugging an existing test.
This is what it would look like if you have an error in one of the commands with this change (with the results also printed out after that as part of the exception).
> throw an error if a command failed

- src/jackdaw/test/commands.clj
- test/jackdaw/test/commands_test.clj
- test/jackdaw/test_test.clj
It's easy to mispell a command, this PR simply throws an exception if any of the commands is unknown to jackdaw.
- throw exception if the command is unknown
- add test
> ensure that the command given in exists

- .circleci/config.yml
Currently, external contributors can never merge their PRs because the circleci `deploy_snapshots` job will always fail. This is because it relies on the `CLOJARS_USERNAME` and `CLOJARS_PASSWORD` env vars, which are not injected for PRs from forks (the "Pass secrets to builds from forked pull requests" option is disabled). 
In circleci, it's not possible to conditionally run a step based on an env var, so this PR just updates the `deploy_snapshot` job to do nothing if `CLOJARS_USERNAME` isn't set.
> Skip deploy_snapshots job for external contributors

- src/jackdaw/client.clj
- test/jackdaw/client_test.clj
Suggested change to address the issue raised in #195 
As the change to the test demonstrates, if the specified timestamp exceeds that of any previously written message, then rather than seek to the beginning of the partition, this change causes the consumer to seek to the end of the partition (and then increment by 1 to get the next message).
Points to note...
- It might be safer not to increment and live with the risk of re-reading a single unwanted message rather than potentially skipping a message due to a race condition.
- The call to `.endOffsets` seems like it might take a while (based on the fact that there is an arity that allows us to specify a timeout). One option to mitigate this is to use a deferred that only gets dereferenced if necessary. This ns doesn't yet depend on …
> Make seek-to-timestamp behave as advertised

- src/jackdaw/streams.clj
- src/jackdaw/streams/configured.clj
- src/jackdaw/streams/interop.clj
- src/jackdaw/streams/protocols.clj
- src/jackdaw/streams/specs.clj
- test/jackdaw/streams_test.clj
Version 2.1 introduced a new operator: [suppress](https://kafka.apache.org/21/documentation/streams/developer-guide/dsl-api.html#window-final-results). It allows to only
forward the final result of a windowed aggregation.
This PR adds the `suppress` function to the streams namespace and
allows for the new operator to be used in Kafka Streams apps. It works but may not be in a final stage. Asking for feedback at this point whether this is what you have in mind or I should change something.
Best
Daniel
> Introduce `suppress` to streams.

- src/jackdaw/test/commands.clj
- src/jackdaw/test/commands/base.clj
- src/jackdaw/test/commands/watch.clj
- src/jackdaw/test/commands/write.clj
- test/jackdaw/test/commands/base_test.clj
- test/jackdaw/test/commands/watch_test.clj
- test/jackdaw/test/commands/write_test.clj
The cmd argument was always passed in every handler but never used.
Since you already know what command you are handling you would probably never need it either, so it can be simplified.
> no need to pass in the cmd in every command handler

- src/jackdaw/serdes/avro.clj
- test/jackdaw/serdes/avro_test.clj
If you have a union type like `["long" "string"]`, the avro serde would fail to serialise a string which contains a numerical value, eg: `"123"`. I added a test case for that. The fix simply checks if the passed value to the `num-coercable?` function is actually a number.
> Only numbers should be num-coercable

- examples/word-count/test/word_count_test.clj
- Timeout was specified incorrectly. This should be a map.
- test-transport contained a reference to a global var when a local version was available.
> Fix word-count-test bugs

- src/jackdaw/streams/interop.clj
- src/jackdaw/test/transports/rest_proxy.clj
- test/jackdaw/test/transports/rest_proxy_test.clj
I'd like to add a capability to the rest-proxy transport that allows a test-author to start consuming the specified topics from the beginning rather than the end. However before getting to that, I wanted to tidy up a few niggling issues so this PR tries to address those.....
* Replace some blocking HTTP calls with asynchronous calls that deal with the response in a callback. This seems to make the rest-proxy transport test that was failing intermittently fail more reliably so...
* Add a small (200ms) delay to the rest-proxy transport constructor which seems to prevent the failure described above from happening at all. I'd love merge a non-sleepy fix to this problem but I'm starting to wonder if it might actually caused by a [race …
> Tidy up the rest-proxy transport

- .circleci/config.yml
💁 Take advantage of a shared context for credentials for deploying to Clojars instead of storing them inline per project.
> Use specific context for deploying to Clojars

- CHANGELOG.md
- src/jackdaw/test.clj
- test/jackdaw/test_test.clj
The actual error returned by jackdaw when something fails is buried in a massive map, with this change it can be printed out directly as the error message and returned as data as well.
> return the error more clearly when something fails

- CHANGELOG.md
- src/jackdaw/test/journal.clj
- test/jackdaw/test/journal_test.clj
Adds functions to simply querying the test-machine journal. These can help make the test machine steps a little more concise:
```clj
(with-open [test-machine (j/test-machine ...)]
(j/run-test test-machine [[:write! :input-topic record]
...
[:watch (j/by-key :output-topic-1 [:status] "success")]]
[:watch (j/by-id :investor-updated (:id investor))
...])]
```
> Add journal access functions

- CHANGELOG.md
Just adding links to one of the changelog entries and prepping for release of 0.7.0
> Prep changelog for release of 0.7.0

- README.md
Now that the release script is working properly, the instructions for cutting a release are quite simple. This PR adds them to the README.
> Add documentation for cutting releases of jackdaw

- CHANGELOG.md
- src/jackdaw/serdes/avro.clj
- test/jackdaw/serdes/avro_test.clj
A few people have noticed that the **JSON** representation of an avro object is a bit different to the edn representation of an avro object. This behaviour was originally copied from the [abracad.avro project](https://github.com/damballa/abracad) but it makes it a little bit inconvenient to work with data obtained via more "avro-oriented" tools like the [kafka-avro-console-consumer](https://github.com/confluentinc/schema-registry/blob/master/bin/kafka-avro-console-consumer) or the [avro-random-generator](https://github.com/confluentinc/avro-random-generator).
The pair of functions in this PR make it a bit easier to convert between these two representations.
```
(as-json {:avro-schema (clojure.data.json/write-str ["null" "string"])}
"yolo")
=> "{\"string\":\"yolo\"}"
```
```
(as-edn …
```
> Open up the coercion stack

- CHANGELOG.md
- src/jackdaw/serdes/avro.clj
- test/jackdaw/serdes/avro_test.clj
When serialising a clojure map to an avro record with a union type schema, the avro serialisation will pick the wrong union type member, and then the serialisation will fail (I'll post a message in slack with more detail). I think the root cause of this is that the `match-clj?` method isn't strict enough for enums and records. I've therefore made this more strict, which fixes the union type serialisation.
> [WB-66] Fix avro union serialisation

- CHANGELOG.md
- src/jackdaw/serdes/avro.clj
- test/jackdaw/serdes/avro_test.clj
Fixes a bug in the Avro deserialisation, which causes it to fail when deserialising a union type composed of enums.
> Fix avro deserialisation for union of enum types

- .gitignore
- CHANGELOG.md
- src/jackdaw/test/commands.clj
- src/jackdaw/test/commands/base.clj
- test/jackdaw/test_test.clj
The test-machine commands are "just data". This allows them to be created using whatever method is convenient (e.g. generated from the contents of some edn file, extracted from a database, read from an existing kafka topic etc.). However when authoring commands from scratch, it can be annoying to have to remember the syntax of each command (or keep referring back to the docs).
This PR adds some functions in the jackdaw.test.commands ns to provide a bit of help for this use-case. Having (spec'd) functions means that tools like cider can give us a bit of interactive help without the need to leave our editor. The specs are very basic for now but we can further refine them (particularly the `::write-options` and `::watch-options` specs) to provide even better assistance. As an example, the …
> Formalizing the test-machine command API

- examples/pipe/src/pipe.clj
This is probably a leftover from copy from word-count example.
> Change application.id config

- project.clj
- test/jackdaw/test/fixtures.clj
Tested as follows:
**Without the dependency**
1. commented out the kafka_2.11 dep in the `project.clj`
2. started a REPL
3. loaded the ` jackdaw.test.fixtures` ns
4. Evaled `((reset-application-fixture {"application.id" "foo" "bootstrap.servers" "dummy"}) (fn []))
` at the REPL from that ns, got this expected result: 
```
Execution error at jackdaw.test.fixtures/reset-application-fixture$fn (form-init9876001671492860525.clj:221).
You must add a dependency on a kafka distrib which ships the kafka.tools.StreamsResetter tool
```
**With the dependency**
1. Started a REPL
2. loaded the ` jackdaw.test.fixtures` ns
3. Evaled `((reset-application-fixture {"application.id" "foo" "bootstrap.servers" "dummy"}) (fn []))
` at the REPL from that ns
The StreamResetter tool was invoked but threw an …
> Remove dependency on org.apache.kafka/kafka_2.11

- CHANGELOG.md
- src/jackdaw/serdes/avro.clj
- src/jackdaw/serdes/avro/confluent.clj
- src/jackdaw/serdes/resolver.clj
- src/jackdaw/specs.clj
- test/jackdaw/serdes/resolver_test.clj
Updates some stale comments.
Changes the spec for avro serdes so that the schema document is optional. This allows a reader to continue using a topic as the producer evolves their schema, without updating the schemas documents in lockstep.
> standalone deser

- src/jackdaw/data/producer.clj
Small reworking to prevent harmless but distracting reflection warnings appearing when creating ProducerRecords.
> Prevent reflection warnings when creating ProducerRecords

- src/jackdaw/test/commands/write.clj
- src/jackdaw/test/serde.clj
- src/jackdaw/test/transports/kafka.clj
- src/jackdaw/test/transports/mock.clj
- src/jackdaw/test/transports/rest_proxy.clj
- test/jackdaw/test_test.clj
Adds basic support to test machine for reading and writing message headers.
Unfortunately, the Kafka Rest API does not appear to support message headers so its not available there - however the broker and mock transports do support headers.
This is deliberately a light touch Test Machine only change to allow testing and experimentation with the support of headers more widely in Jackdaw, or any topologies tested via Test Machine. No attempt at serdes support is added here, headers must be provided in the form the Java API expects which is a map of:
`String k` -> `byte[] value`
The support does at least let you provide them in a clojure Map. Writes are supported via an additional option for the `:write!` command, e.g.:
`[:write! "my-topic" {:id 1 :message "yolo"} {:headers {"VERSION" …
> Add kafka message header support for test machine

- CHANGELOG.md
> changelog updates for 0.7.7

- CHANGELOG.md
- project.clj
> Override Netty version to fix CVE-2020-11612

- doc/client.md
- add documentation about `subscribed-consumer` function and how to use it
-  add missing polling interval parameter for consumer `log` function, and mention optional `fuse-fn` parameter and its use
> Add missing info to Jackdaw Client API documentation

- CHANGELOG.md
- project.clj
Bump netty related packages from `4.1.59.Final` to `4.1.63.Final`
> bump netty related packages to latest version

- .circleci/config.yml
- CHANGELOG.md
Is failing due to fallback to v1-jackdaw-* and matching with v1-jackdaw-deps
> fix(ci): add -repo to repo cache names to not match with deps cache

- .circleci/config.yml
- CHANGELOG.md
- project.clj
- src/jackdaw/streams/lambdas.clj
- src/jackdaw/test/fixtures.clj
- test/jackdaw/serdes/avro_test.clj
> Update to kafka streams 2.8.0 (confluent 6.1.1)

- CHANGELOG.md
- src/jackdaw/streams.clj
- src/jackdaw/streams/configured.clj
- src/jackdaw/streams/interop.clj
- src/jackdaw/streams/protocols.clj
- src/jackdaw/streams/specs.clj
- test/jackdaw/streams_test.clj
This PR adds support for KStream-KTable inner joins. See the commit message for details.
> Add KStream-KTable inner join

- CHANGELOG.md
- project.clj
- src/jackdaw/serdes/fn_impl.clj
- src/jackdaw/serdes/json_schema/confluent.clj
- src/jackdaw/serdes/resolver.clj
- test/jackdaw/serdes/json_schema/confluent_test.clj
- test/jackdaw/serdes/resolver_test.clj
- test/resources/example_json_schema.json
> JSON Schema SERDE

- CHANGELOG.md
- src/jackdaw/streams.clj
- src/jackdaw/streams/interop.clj
- src/jackdaw/streams/lambdas.clj
- src/jackdaw/streams/mock.clj
- src/jackdaw/streams/protocols.clj
- src/jackdaw/streams/specs.clj
- src/jackdaw/test.clj
- test/jackdaw/streams_test.clj
* added simple helpers in `lambdas` for using transformers more easily in a stream
* added the `flatTransform` and `flatTransfromValues` calls to the core streams interface
* added a helper function to add KV state stores to a streams builder
> Some additions and helpers for Kafka Streams interop

- CHANGELOG.md
- project.clj
Fixes CVE-2021-37137, CVE-2021-37136 and CVE-2021-36090. Moving overrides in dependency management as it keeps the structure of the dependency tree as is instead of adding the overriding libs as top level deps.
> Fix CVEs for netty and apache commons-compress

- CHANGELOG.md
- project.clj
Dependency management doesn't propagate to upstream projects.
> Move library overrides back to dependencies

- CHANGELOG.md
- src/jackdaw/serdes/avro.clj
Avro error messages now include the relevant path and topic.
On type errors:
- the path points to the attribute that caused the error
- we'll also include the data of said attribute
On any other error (e.g missing/unknown):
- the path points to the map the attribute that caused the error belongs
**Error message examples**
Incorrect Union type - `:my-attribute` is an enum and we supply a string:
```
{:message "java.lang.String is not a valid type for union [NULL, ENUM]", :path [:my-attribute], :data "Something", :topic "topic-name-1"}
```
Incorrect type for nested field `:name` of map `:person`:
```
{:message "java.lang.Long is not a valid type for string", :topic "topic-name-1", :path [:person :name], :data 123}
```
Unknown field `:application-id2` in top level:
```
{:message "Field …
```
> [TDI-1361] make the avro serialization exception message more verbose

- CHANGELOG.md
- src/jackdaw/data/producer.clj
- src/jackdaw/streams/mock.clj
- test/jackdaw/streams_test.clj
This change removes dependency on the obsolete [test classes that have been removed](https://github.com/apache/kafka/pull/10508) in Kafka 3.0, paving the way for an upgrade. See this article for more context about this removal: https://www.confluent.io/en-gb/blog/test-kafka-streams-with-topologytestdriver/
> Move away from deprecated class ConsumerRecordFactory

- CHANGELOG.md
This page is currently broken https://cljdoc.org/d/fundingcircle/jackdaw/0.9.6/doc/readme
> Trivial release to fix API publishing in cljdocs

- .gitignore
- CHANGELOG.md
- src/jackdaw/admin.clj
- src/jackdaw/test/commands/base.clj
v0.9.10 introduced some reflection warnings. Whilst harmless seeing `.deleteTopics` appear in your logs at app startup is a little unsettling.
> fix reflection warnings

- src/jackdaw/test/transports/mock.clj
This [change](https://github.com/FundingCircle/jackdaw/commit/7f6092fd4bcc5d5e4dc7f58fe9cbcd0c1f0dfe94#diff-92e819e2014b251ee6134168dbe5af6cb558a846ee7a06d23b0a0b6ae40b7a14R178-R182) broke the previous behavior where the consumer records included timestamp.
This is critical for tests suites asserting windowed results that pushes consumer records to control stream time.
> test.transport.mock: pipeInput input-record to mimic old behaviour

- project.clj
> add manifold and keep aleph in dev dependencies

- src/jackdaw/client.clj
- test/jackdaw/client_test.clj
This fixes #371 — thanks to @djeis97 for spotting.
> Fix seek-to-timestamp
